# Generated by Django 3.0.8 on 2020-12-06 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheSparkFoundation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='CurrBal',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='customers',
            name='Name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
