# Generated by Django 3.0.8 on 2020-12-06 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheSparkFoundation', '0002_auto_20201206_2244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='CurrBal',
            new_name='Current_Balance',
        ),
        migrations.AddField(
            model_name='customers',
            name='Email',
            field=models.EmailField(default='none@none.com', max_length=250),
        ),
    ]
