# Generated by Django 3.0.8 on 2020-12-09 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheSparkFoundation', '0003_auto_20201206_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='Account_Number',
            field=models.CharField(default='123456789', max_length=50),
        ),
        migrations.AddField(
            model_name='customers',
            name='Address',
            field=models.CharField(default='abcd', max_length=150),
        ),
        migrations.AddField(
            model_name='customers',
            name='Branch_Code',
            field=models.CharField(default='023F', max_length=20),
        ),
        migrations.AddField(
            model_name='customers',
            name='IFSC_Code',
            field=models.CharField(default='FR1234567890', max_length=50),
        ),
        migrations.AddField(
            model_name='customers',
            name='Phone_Number',
            field=models.CharField(default='9999999999', max_length=10),
        ),
    ]
